---

- name: Enable bluetooth service
  service:
    name: bluetooth.service
    state: started
    enabled: yes

- name: Enable SDD service
  service:
    name: sddm
    state: started
    enabled: yes
