---

- name: Install basic packages
  pacman:
    name:
      - htop
      - btop
      - cmake
      - stow
      - openssh
      - rofi
      - podman
      - links
      - fzf
      - curl
      - wget
      - podman-compose
      - distrobox
      - ttf-fira-code
      - ttf-firacode-nerd
      - ttf-hack-nerd
      - ttf-dejavu
    state: present
