---

- name: Install basic packages
  pacman:
    name: 
      - htop
      - btop
      - cmake
      - stow
      - openssh
      - rofi
      - podman
      - links
      - curl
      - wget  
      - podman-compose
      - distrobox
      - ttf-fira-code
      - ttf-firacode-nerd
      - ttf-hack-nerd
    state: present


