---

- name: Install virtualenv
  pacman:
    name: python-virtualenv
    state: present
  tags:
    - python
    - programming-languages


- name: Install pyenv
  pacman:
    name: pyenv
    state: present
  tags:
    - python
    - programming-languages

- name: Install pyenv-virtualenv plugin
  become: false
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ home_path }}/.pyenv/plugins/pyenv-virtualenv"
  tags:
    - python
    - programming-languages

- name: Install pip
  pacman:
    name: python-pip
    state: present
  tags:
    - python
    - programming-languages

- name: Install Ruby
  pacman:
    name: ruby
    state: present
  tags:
    - ruby
    - programming-languages

- name: Install Shellcheck
  pacman:
    name: shellcheck
    state: present
  tags:
    - bash
    - programming-languages

- name: Install bash language server
  pacman:
    name: bash-language-server
    state: present
  tags:
    - bash
    - programming-languages
