---

- name: Install terminal utilitaries
  pacman:
    name:
      - alacritty
      - zsh
      - bat
      - ripgrep
    state: present

- name: Set zsh as default shell
  shell: "chsh -s /usr/bin/zsh {{ local_user }}"


- name: Install starship
  become: false
  command: "cargo install starship"

- name: Install zellij
  become: false
  command: "cargo install zellij"
