---

- name: Install terminal utilitaries
  pacman:
    name:
      - alacritty
      - bat
      - ripgrep
    state: present

- name: Install starship
  become: false
  command: "cargo install starship"

- name: Install zellij
  become: false
  command: "cargo install zellij"

- name: Install zoxide
  become: false
  command: "cargo install zoxide --locked"
